name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  lint-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8

      - name: Lint (black)
        run: black --check .

      - name: Lint (flake8)
        run: flake8 .

      - name: Import smoke test
        run: |
          python - <<'PY'
          import importlib
          importlib.import_module("app")
          print("app imported OK")
          PY
